### ISSUE TITLE
SECURITYCENTER env nessus-monitor

### ISSUE THREAD

**Issue by MatteoManzoni** [SteveMcGrath/docker-nessus_monitor#1]
Hi!
I'm in the process to deploy your great nessus monitor container and I was thinking if it's possible to link it to my instance of tenable.sc.

With the nessus scanner everything went smoothly setting SECURITYCENTER to Yes and providing the admin password to my tenable.sc console, it is possible to replicate it with the nessus monitor?

Have a great day!
Matteo

**Comment by SteveMcGrath** [comment]
I'd have to review the flags, but I think its as simple as passing "SECURITYCENTER" into the license.  Below is the file that handles the initial setup.

https://github.com/SteveMcGrath/docker-nessus_monitor/blob/master/nessus.sh

**Comment by MatteoManzoni** [comment]
Tomorrow I'll try and report back, thank you!

**Comment by MatteoManzoni** [comment]
I can confirm that after setting license key to SECURITYCENTER everything went smoothly
